### ISSUE TITLE
UltiMaze Error when activating add-on in user preferences. 

### ISSUE THREAD

**Issue by choyce7** [ekaj2/UltiMaze#3]
Here is the error I receive when trying to activate the add-on in user preferences.  I am working on windows 7, using blender 2.78c.  Got the same error in 2.78a.  

![maze error](https://user-images.githubusercontent.com/15334394/27988761-4d5e77c2-63f0-11e7-9ddf-bf21db234cde.png)

**Comment by ekaj2** [comment]
@choyce7 Thanks for submitting this issue. I will look into this as soon as possible. Unfortunately, the error appears to be in a third party module...

**Comment by ekaj2** [comment]
@choyce7 I just submitted an update...does [this](https://github.com/ekaj2/UltiMaze/archive/master.zip) fix your issue?

**Comment by choyce7** [comment]
Yes it did!  What was wrong?  Thank you so much!

**Comment by ekaj2** [comment]
@choyce7 I use the [add-on updater tool from CGCookie](https://github.com/CGCookie/blender-addon-updater) to automatically check for and install updates. The issue is that there is not a good way to automatically update that module when they update it. I have to manually go in copy/paste + edit + test to include changes in my add-ons. Since your issue was in that module and seemed very strange, I figured I would try updating that module which I haven't done in months.

Thanks for the info, and have fun with UltiMaze!
